### ISSUE TITLE
Error output when applying to k8s

### ISSUE THREAD

**Issue by sang-w0o** [aws/amazon-vpc-resource-controller-k8s#127]
**Describe the Bug**:

Hello, I am using `SecurityGroupPolicy` and observed an error output.

The result is working as expected, but the log generates output.

My yaml file is as below.

```yaml
apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: ${NAME}
  namespace: ${NAMESPACE}
spec:
  podSelector:
    matchLabels:
      foo: bar
  securityGroups:
    groupIds:
      - ${VALID_SECURITY_GROUP_ID}
```

As I mentioned above, this works perfectly, but when I run `kubectl logs`, I get an output below.

```
❯ kubectl logs -n planit-dev securitygrouppolicy.vpcresources.k8s.aws/${NAME}
error: no kind "SecurityGroupPolicy" is registered for version "vpcresources.k8s.aws/v1beta1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"
```

This output give some frustrations to users, and should be fixed.
