### ISSUE TITLE
Are policies not additive?

### ISSUE THREAD

**Issue by mikkoc** [aws/amazon-vpc-resource-controller-k8s#284]
Hi there,

We are currently in the early stages of evaluating Security Groups for Pods to restrict/control network flows in and out of our EKS cluster.

I am looking for any best practises that you are able to share.
I have already read these: 
[https://aws.github.io/aws-eks-best-practices/networking/sgpp/ ](https://aws.github.io/aws-eks-best-practices/networking/sgpp/)
[https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html ](https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html)
https://aws.amazon.com/blogs/containers/introducing-security-groups-for-pods/

More specifically, I have a couple of questions:

1) Are the policies not additive? For example: if I have a generic policy to allow all traffic inside the cluster. This policy is without any PodSelector, it applies to all the pods in the namespace. But then I have another policy that I want to apply to a single pod, so I pass the matchLabels option to match only that pod. But I also need to specify the SecurityGroup ID from my generic policy: it does not "add" it. Why? This is very counterintuitive, and bad. See attached YAML file as example.

2) Why is there a max limit of 5 SGs (*) per Policy, given we can raise the limit in EC2? Given my point 1), I expect I might have to have more than that. As a matter of fact, we currently have a service that already has 4 SecurityGroups associated, and we haven't even started yet!

3) While looking for best practises and lessons learned about PodSecurityGroup (I didn't find much, hence my ask). I ran into this comment: [https://github.com/cilium/cilium/issues/23209#issuecomment-1552551716 ](https://github.com/cilium/cilium/issues/23209#issuecomment-1552551716) which scares me a little bit. Especially since the comment is from an ex-AWS employee. Do you have any major customer using this feature? Or is it better for small scale players? Any performance issues at scale? I don't want to go down a rabbit hole and then find out this does not scale or has random issues.

Thanks

**Describe the Bug**:

**Observed Behavior**:
Policies do not "add"

**Expected Behavior**:
I would expect policies to be additive: if the same pod is matched by 2 policies, the SGs from both policies should be applied to the pod. Instead, the same SG needs to be added to both policies. In my example it's `sg-0a844fab52643045d`

**How to reproduce it (as minimally and precisely as possible)**:

```
apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: all-pods
spec:
  securityGroups:
    groupIds:
      - sg-0a844fab52643045d # intra-cluster
---
apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: consumers
spec:
  podSelector:
    matchLabels:
      role: consumer
  securityGroups:
    groupIds:
      - sg-0a844fab52643045d # intra-cluster (why is this needed?!)
      - sg-08f821984ad2144c4 # mongodb
      - sg-04c142a63393cba20 # eventstore
```

**Additional Context**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.24
- CNI Version: 1.13.2-eksbuild.1
- OS (Linux/Windows): AL2
