### ISSUE TITLE
Update SecurityGroupPolicy.spec.securityGroups Interface to accept Security Group Names

### ISSUE THREAD

**Issue by seanturner026** [aws/amazon-vpc-resource-controller-k8s#292]
**What would you like to be enhanced**:

Currently the `SecurityGroupPolicy` only supports hardcoded Security Group IDs.

```yaml
apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
spec:
  securityGroups:
    groupIds:
      - sg-0123456789
```

It would be handy if `SecurityGroupPolicy.spec.securityGroups` exposed a way to look up a security group by tags or by security group name, rather than just by ID. 

**Why is the change needed and what use case will it solve**:

I am not familiar with an easy way to programmatically get the Security Group ID into this resource definition. Anything I come up with is fairly convoluted.

Additionally, an actual security group name would be more explicit than an arbitrary ID. 

Finally, if `sg-0123456789` is destroyed and re-created, I need to update the Security Group ID. However, if the Security Group is created with the same name, this resource would not need to be updated.
