### ISSUE TITLE
Pods fail to bring up networking when security groups are used

### ISSUE THREAD

**Issue by interone-ms** [aws/amazon-vpc-resource-controller-k8s#348]
**Describe the Bug**:
Pods that are affected by a security group policy in about 20% of cases do not start correctly, and basic connectivity such as DNS fails, thus breaking our deployment of Gitlab pipelines. The problem has been going on for weeks, we managed to narrow it down to IPAM.

<details>
<summary>Security Group Policy:</summary>

```yaml
apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: xxx
  namespace: gitlab-runner
spec:
  podSelector: {}
  securityGroups:
    groupIds:
    - sg-a
    - sg-b
    - sg-c
```

</details>

<details>
<summary>Pod:</summary>

[pod.txt](https://github.com/aws/amazon-vpc-resource-controller-k8s/files/13704452/pod.txt)

</details>

<details>
<summary>`/var/log/aws-routed-eni/ipamd.log` on the machine:</summary>

[ipamd.log](https://github.com/aws/amazon-vpc-resource-controller-k8s/files/13704457/ipamd.log)

</details>

**Observed Behavior**:

The pod does start, but operations like `git clone` fail:

```
fatal: unable to access 'https://xxx/yyy.git/': Could not resolve host: xxx.de
```

CoreDNS logs (obtained from `kubectl logs -f deployment.apps/coredns --all-containers=true`) do not show any queries originating from the pod's IP.

**Expected Behavior**:

Pod networking comes up normally, there are no warnings such as `failed to assign an IP address to container` in the events.

**How to reproduce it (as minimally and precisely as possible)**:

Create a blanket security group that targets an entire namespace, try to start a pod in it, observe it failing.

```Dockerfile
FROM ubuntu:22.04 as base
RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
 DEBIAN_FRONTEND=noninteractive apt-get -yf dist-upgrade && \
 DEBIAN_FRONTEND=noninteractive apt-get -yf install curl bind9-dnsutils net-tools iproute2 && \
 DEBIAN_FRONTEND=noninteractive apt-get clean && \
 rm -rf /var/lib/apt/lists/*
```

```yaml
---
apiVersion: v1
data:
  .dockercfg: xxx
kind: Secret
metadata:
  name: runner-test
  namespace: gitlab-runner
type: kubernetes.io/dockercfg
---
apiVersion: v1
kind: Pod
metadata:
  name: runner-test
  namespace: gitlab-runner
spec:
  dnsConfig:
    options:
      - name: ndots
        value: "1"
  imagePullSecrets:
    - name: runner-test
  containers:
    - name: app
      command:
        - sh
        - '-c'
        - 'ip addr && ip route && cat /etc/resolv.conf && dig xxx.de && curl -v https://xxx.de'
      image: pathtoimagefromabove
      imagePullPolicy: Always

```

**Additional Context**:

We suspect this is a similar issue to #118 or https://github.com/aws/amazon-vpc-cni-k8s/issues/1245.

The EKS nodes run in their own subnet, with a NAT gateway providing connectivity. The subnets have thousands of IPs free each.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.26.11-eks-8cb36c9 (AWS EKS 1.26)
- CNI Version: `vpccni` addon managed by EKS, version `v1.15.4-eksbuild.1`, configuration
```
        {
            enableWindowsIpam = "true"
            env               = {
                AWS_VPC_K8S_CNI_EXTERNALSNAT = "true"
                ENABLE_POD_ENI               = "true"
            }
        }
```
- OS (Linux/Windows): Linux, AWS AMI release 1.26.10-20231201, running on c5a.4xlarge instance
