### ISSUE TITLE
Rename vpc.amazonaws.com/PrivateIPv4Address on Capacity and Allocatable Spec

### ISSUE THREAD

**Issue by maiconrocha** [aws/amazon-vpc-resource-controller-k8s#425]
Currently, we have _"vpc.amazonaws.com/PrivateIPv4Address"_  being used on Capacity and Allocatable spec, also on the Annotations.

For Capacity and Allocatable the value is a number, and on the annotation the value will be the actual IPv4Address

For example:
```
Capacity:
  vpc.amazonaws.com/PrivateIPv4Address:  9
Allocatable:
  vpc.amazonaws.com/PrivateIPv4Address:  9
```
```
Annotations:    
  vpc.amazonaws.com/PrivateIPv4Address: 192.168.25.15/19
```
I noticed this creates confusion for customers and also for me.

Can we rename the _"vpc.amazonaws.com/PrivateIPv4Address"_ to _"vpc.amazonaws.com/PrivateIPv4AddressCapacity"_ on Capacity
and _"vpc.amazonaws.com/PrivateIPv4AddressAllocatable"_ to Allocatable to avoid confusion with the annotation _"vpc.amazonaws.com/PrivateIPv4Address"_?
Thank you

**Comment by jiechen0826** [comment]
Hi @maiconrocha, as @sushrk called out above, this is a naming convention followed by multiple resources throughout the repo, it might need some refactoring to change the name. We would like to understand more the rationale behind updating the resource name. Could you please let us know what the impact is if we don't change the name?

**Comment by haouc** [comment]
@maiconrocha unless you have special use case which leads to confusions on those annotations, we are following the same naming convention on node `capacity` and `allocatable` fields. If you describe a node and you will see the pattern
For example:
```
  allocatable:
    cpu: 1930m
    ephemeral-storage: "18242267924"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 3097528Ki
    pods: "29"
    vpc.amazonaws.com/pod-eni: "9"
  capacity:
    cpu: "2"
    ephemeral-storage: 20959212Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 3787704Ki
    pods: "29"
    vpc.amazonaws.com/pod-eni: "9"
```

I am closing this request and please feel free to reopen if this still concerns you. Thanks
