### ISSUE TITLE
CNINode resources' name should refecting to node's instance ID

### ISSUE THREAD

**Issue by haouc** [aws/amazon-vpc-resource-controller-k8s#515]
**What would you like to be enhanced**:
Currently the CNINode resources' name are node hostname which is likely reused by EC2. To be more resilient, using instance ID should be a better way to prevent collision.

**Why is the change needed and what use case will it solve**:
Hypothetically, if the resources were leaked, the name collision would cause breaking behavior on this controller.

**Comment by zshen-figma** [comment]
Hi do we have timeline on solving this issue?

**Comment by cdirubbio** [comment]
A workaround is using https://awslabs.github.io/amazon-eks-ami/nodeadm/doc/examples/#using-instance-id-as-node-name in the meantime
```
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="BOUNDARY"

--BOUNDARY
Content-Type: application/node.eks.aws

---
apiVersion: node.eks.aws/v1alpha1
kind: NodeConfig
spec:
  featureGates:
    InstanceIdNodeName: true

--BOUNDARY--
```

Note, this requires using an Access Entry of type `EC2` rather than `EC2_LINUX` which is the default. This is because the username needs to be the session name (instance id), rather than the private IPv4 DNS Name. If you are using Managed Node Groups, you will need to delete the auto-created Access Entry of type `EC2_LINUX` and create a new one for `EC2`. For Karpenter, similarly you need to create the `EC2` access entry, and here is example nodeclass configuration:
```
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: al2023
spec:
  amiFamily: AL2023
...
  userData: |
    MIME-Version: 1.0
    Content-Type: multipart/mixed; boundary="//"

    --//
    Content-Type: application/node.eks.aws

    apiVersion: node.eks.aws/v1alpha1
    kind: NodeConfig
    spec:
      featureGates:
        InstanceIdNodeName: true

    --//
```
